[package]
description = "iced wayland widget center"
edition = "2024"
name = "iwwc"
version = "0.1.0"

[dependencies]
# base deps
clap = { version = "4.5.41", features = ["derive"] }
log = "0.4.27"
env_logger = "0.11.8"
tokio = { version = "1.46.1", features = ["full"] }
tokio-stream = "0.1.17"
once_cell = "1.21.3"
toml = "0.9.2"
serde = { version = "1.0", features = ["derive"] }
serde_yml = "0.0.12"

# backend deps
zbus = "5.8.0"

# frontend deps
iced = { git = "https://github.com/iced-rs/iced.git", features = [
	"tokio",
	"svg",
]}
iced_layershell = { git = "https://github.com/id3v1669/exwlshelleventloop.git", rev = "aada765" }
futures = "0.3.31"
indexmap = "2.10.0"

[profile.release]
opt-level = "z"
lto = true          # Enable Link Time Optimization
codegen-units = 1   # Reduce number of codegen units to increase optimizations.
strip = true        # Strip symbols from binary*

