[package]
description = "notifications center and daemon"
edition = "2021"
name = "rs-nc"
version = "0.0.0"

[dependencies]
# base deps
clap = { version = "4.5.21", features = ["derive"] }
env_logger = "0.11.5"
log = "0.4.22"
tokio = { version = "1.41.1", features = ["full"] }
tokio-stream = "0.1.16"
once_cell = "1.20.2"
toml = "0.8.19"
serde = { version = "1.0", features = ["derive"] }

# backend deps
zbus = "4.4.0"

# frontend deps
iced = { git = "https://github.com/iced-rs/iced.git", rev = "f2c9b6b2ffc50d67d9789e77cb55eeb2a0ebe470" , features = [
	"tokio",
	"svg",
]}
iced_layershell = { git = "https://github.com/id3v1669/exwlshelleventloop.git", rev = "44644c14d02ff39c70c13a93c5f272094a55b1e5" }
futures = "0.3.30"


