[package]
description = "iced wayland widget center"
edition = "2024"
name = "iwwc"
version = "0.1.0"

[dependencies]
# base deps
clap = { version = "4.5.42", features = ["derive"] }
log = "0.4.27"
env_logger = "0.11.8"
tokio = { version = "1.47.1", features = ["full"] }
tokio-stream = "0.1.17"
once_cell = "1.21.3"
toml = "0.9.5"
serde = { version = "1.0", features = ["derive"] }
serde_yml = "0.0.12"

# backend deps
zbus = "5.9.0"

# frontend deps
iced = { version = "0.14.0-dev", git = "https://github.com/iced-rs/iced.git", features = [
	"tokio",
	"svg",
	"wgpu"
]}
iced_layershell = { version = "0.14.0-dev", git = "https://github.com/id3v1669/exwlshelleventloop.git", rev = "ff979054e02f6251c586e088aa7d58aca3cdfcac" }
futures = "0.3.31"
indexmap = "2.10.0"



